export const GET_RENTALS = "GET_RENTALS";
export const POST_RENTAL = "POST_RENTAL";
export const POST_MACHINE = "POST_MACHINE";
export const GET_MACHINES = "GET_MACHINES";
export const GET_RENTAL_BY_ID = "GET_RENTAL_BY_ID";
export const UPDATE_RENTAL = "UPDATE_RENTAL";
export const GET_MACHINE_BY_ID = "GET_MACHINE_BY_ID";
export const MOST_RENTED_MACHINE = "MOST_RENTED_MACHINE";

//---------- BEGIN EARNINGS -------------//
export const GET_EARNINGS = "GET_EARNINGS";
export const GET_EARNINGS_BY_MONTH = "GET_EARNINGS_BY_MONTH";
export const GET_EARNINGS_PER_DAY  = "GET_EARNINGS_PER_DAY";
export const GET_EARNINGS_WIFI_PER_DAY  = "GET_EARNINGS_WIFI_PER_DAY";
export const GET_EARNINGS_PER_MONTH = "GET_EARNINGS_PER_MONTH";
export const GET_EARNINGS_PER_CASH_PAYMENTS = "GET_EARNINGS_PER_CASH_PAYMENTS";
export const GET_EARNINGS_PER_MOBILE_PAYMENTS = "GET_EARNINGS_PER_MOBILE_PAYMENTS";
export const GET_ALL_INCOME_MOVEMENTS = "GET_ALL_INCOME_MOVEMENTS";
//---------- END EARNINGS -------------//

export const GET_STATUS_EARNINGS = "GET_STATUS_EARNINGS";
export const GET_REVENUE_LAST_MONTH = "GET_REVENUE_LAST_MONTH";
export const GET_MOVEMENTS = "GET_MOVEMENTS";
export const POST_MOVEMENT = "POST_MOVEMENT";
export const GET_MOVEMENT_BY_ID = "GET_MOVEMENT_BY_ID";

export const GET_RENTAL_WIFI = "GET_RENTAL_WIFI";
export const POST_RENTAL_WIFI = "POST_RENTAL_WIFI";
export const GET_RENTALWIFI_BY_ID = "GET_RENTALWIFI_BY_ID";


export const GET_COUNT_RENTALS = "GET_COUNT_RENTALS";


export const GET_VALUE_DOLLAR = "GET_VALUE_DOLLAR";

//---------- BEGIN USERS -------------//
export const GET_USERS = "GET_USERS";
export const POST_USER = "POST_USER";
export const GET_USERS_BY_ID = "GET_USERS_BY_ID";
export const GET_USERS_BY_MAC = "GET_USERS_BY_MAC";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USER_BY_NAME = "GET_USER_BY_NAME";
//---------- END USERS -------------//